[tools]
"pipx:check-jsonschema" = "0.37.4"
pre-commit = "latest"

[tasks.lint]
description = "Check Nix files with deadnix, nixpkgs-fmt, and statix"
run = '''
#!/usr/bin/env bash
set -euo pipefail

nix --extra-experimental-features "nix-command flakes" run nixpkgs#deadnix -- --fail .
nix --extra-experimental-features "nix-command flakes" run nixpkgs#nixpkgs-fmt -- --check .
nix --extra-experimental-features "nix-command flakes" run nixpkgs#statix -- check .
'''

[tasks."lint:fix"]
description = "Auto-fix Nix files with deadnix, nixpkgs-fmt, and statix"
run = '''
#!/usr/bin/env bash
set -euo pipefail

nix --extra-experimental-features "nix-command flakes" run nixpkgs#deadnix -- --edit .
nix --extra-experimental-features "nix-command flakes" run nixpkgs#nixpkgs-fmt -- .
nix --extra-experimental-features "nix-command flakes" run nixpkgs#statix -- fix .
'''
